version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  build:
    commands:
      - pip install --user aws-sam-cli
      - >-
        aws cloudformation package --template template-hw.yaml --s3-bucket
        $S3_BUCKET --output-template template-export-hw.json
artifacts:
  type: zip
  files:
    - template-export-hw.json
