version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  build:
    commands:
      - pip install --user aws-sam-cli
      - >-
        sam build --template-file sam/template.yaml --build-dir
        sam/.aws_sam/build
      - >-
        sam package --template-file "sam/.aws_sam/build/template.yaml"
        --output-template-file "sam/.aws_sam/package/template.yaml"
      - >-
        aws cloudformation package --template sam/.aws_sam/package/template.yaml --s3-bucket
        $S3_BUCKET --output-template template-export-states.json
artifacts:
  type: zip
  files:
    - template-export-states.json
